### ISSUE TITLE
oukitel k4000 plus

### ISSUE THREAD

**Issue by bgman111111** [mhdzumair/MhDzMR-kernel#1]
hi can you integrade lcm driver rm6820... i will give you if you integrate it. I wan compile latest android. And if you make general mediatek work for all mediatek mediatek smartphones

**Comment by mhdzumair** [comment]
Ok sure. let me try to integrate. give the details

**Comment by bgman111111** [comment]
Thank you.

zte blade a610: https://github.com/bgman111111/zte-blade-a610-european-version if i remember it is untouched version.

oukitel k4000 plus: https://bgzashtita.es/git/Android-smartphones/oukitel/k4000/android_device_oukitel_k4000pro/uploads/415791e7d8fda4af31981d37aee7f444/K4000_Plus.html
it has all hwinfo+ information.

https://github.com/mrmazakblu/Android_Kernel_Blu_Tank_Xtreme_Pro_T0010UU/tree/master/drivers/misc/mediatek/lcm rm68200_hd720_dsi_vdo_f502_s21_dt 

zte blade a610 is pure 6735. oukitel k4000 plus is combo, mt6735 and 6737m. but use strange lcm driver. Khiru from 4pda make it work, becouse he make twrp and in hex it was not rm6820... if i remember it was different driver. So here is what i collect: 

https://bgzashtita.es/git/Android-smartphones/oukitel/k4000
https://bgzashtita.es/git/Android-smartphones/zte/blade-a610

in zte blade a610 porting section there is k5fpr it has devices that are working with android 10. when everything is working i think clean it and leave that is what is working. there is way to make old mediatek devies work. I try compile android 10 wit alps but it was failing on missing fdfamework so i add it two if them for arm64 and it continue compile " unknown if it gonna work " becouse arm64 was copied from mt6739, but it fail to compile on incorrect drivers. So how i see, it is possible to make old mediatek but we need hackers who like developer

**Comment by mhdzumair** [comment]
Thanks. ill do my best. ill close this issue. Contact me on Telegram id: @Mohamed_Zumair
